export const INDUSTRIES: string[] = [
  'Air Conditioning',
  'Appliance Repair',
  'Asphalt & Paving',
  'Audio Visual',
  'Carpentry',
  'Chimney',
  'Cleaning',
  'Commercial Services',
  'Concrete',
  'Construction',
  'Drywall',
  'Electrical',
  'Elevator',
  'Fencing',
  'Fire Protection',
  'Flooring',
  'Garage Door',
  'General Contractor',
  'Glass & Glazing',
  'Handyman',
  'HVAC',
  'Insulation',
  'Interior Design',
  'Irrigation',
  'Janitorial',
  'Landscaping',
  'Lawn Care',
  'Locksmith',
  'Marine',
  'Masonry',
  'Mechanical',
  'Moving',
  'Painting',
  'Pest Control',
  'Plumbing',
  'Pool & Spa',
  'Power Washing',
  'Property Management',
  'Refrigeration',
  'Remodeling',
  'Restoration',
  'Roofing',
  'Security',
  'Septic',
  'Siding',
  'Snow Removal',
  'Solar',
  'Stone & Tile',
  'Tree Service',
  'Waterproofing',
  'Welding',
  'Window Treatment',
]
